### ISSUE TITLE
ERROR: cannot load plugin `dot`

### ISSUE THREAD

**Issue by bitfhacker** [jawher/markdown-dot#1]
When I "pelican content' the following message appears:

ERROR: Cannot load plugin `dot`
  | No module named dot

I included the dot plugin in configuration. What I'm doing wrong?

**Comment by jawher** [comment]
Make sure that the dot extension is first installed using pip or easy_install, and then in the pelicanconf.py, add `dot` to the list of markdown extensions:

``` Python
MD_EXTENSIONS = ['codehilite', 'extra', 'toc', 'fenced_code', 'dot']
```

**Comment by bitfhacker** [comment]
It worked fine, thanks!

Note: I had to disable cache.
